blank_issues_enabled: false
contact_links:
  - name: Angler Community Support
    url: https://github.com/evan-palmer/angler/discussions
    about: Please check out our discussions channel for any questions related to the project!
