# Plan a sequence of waypoints for the AUVMS to track.

std_msgs/Header header

# The maximum amount of time that the planner has to generate a trajectory.
# This can be used by anytime algorithms (e.g., Anytime A*).
float64 timeout

# The current pose of the robot.
geometry_msgs/Pose current_pose

# The target pose that the robot should navigate to.
geometry_msgs/Pose goal_pose
---
# Return a task-plan that the robot should execute.
angler_msgs/Waypoint[] mission
---
# No feedback is provided.

