aruco_marker_detector:
  ros__parameters:
    port: 5600
    camera_matrix:
      [1078.17559, 0.0, 1010.57086, 0.0, 1076.46176, 463.06243, 0.0, 0.0, 1.0]
    distortion_coefficients:
      [0.019645, 0.007271, -0.004324, -0.001628, 0.000000]
    projection_matrix:
      [
        1108.25366,
        0.0,
        1003.75555,
        0.0,
        0.0,
        1108.39001,
        456.92861,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ]

preplanned_mission_planner:
  ros__parameters:
    mission_name: "straight"
