joy_node:
  ros__parameters:
    dev: /dev/input/js0

joy_interface:
  ros__parameters:
    trims:
      min_pwm: 1300
      max_pwm: 1700

joy_teleop:
  ros__parameters:

    arm_ardusub:
      type: service
      interface_type: mavros_msgs/srv/CommandBool
      service_name: /mavros/cmd/arming
      service_request:
        value: True
      buttons: [7]

    disarm_ardusub:
      type: service
      interface_type: mavros_msgs/srv/CommandBool
      service_name: /mavros/cmd/arming
      service_request:
        value: False
      buttons: [6]

    arm_angler:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /angler/cmd/arm_autonomy
      deadman_buttons: [5]
      message_value:
        data:
          value: True

    disarm_angler:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /angler/cmd/arm_autonomy
      deadman_buttons: [4]
      message_value:
        data:
          value: False

    start_mission:
      type: topic
      interface_type: std_msgs/msg/Empty
      topic_name: /angler/cmd/start_mission
      deadman_buttons: [2]
      message_value:

    manual_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: MANUAL
      buttons: [0]

    depth_hold_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: ALT_HOLD
      buttons: [1]

    manual_control:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: /blue/joy_interface/cmd_vel
      deadman_axes: [2]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.5
          offset: 0
        linear-y:
          axis: 0
          scale: 0.5
          offset: 0
        linear-z:
          axis: 4
          scale: 0.5
          offset: 0
        angular-z:
          axis: 3
          scale: 1.0
          offset: 0
