preplanned_end_effector_planner:
  ros__parameters:
    trajectory_name: "straight"

tpik:
  ros__parameters:
    constraint_config_path: "/workspaces/angler/angler_description/config/tasks.yaml"
    manipulator_base_link: "alpha_base_link"
    manipulator_end_link: "alpha_standard_jaws_tool"
    control_rate: 50.0 # Hz
