- task: "joint_limit"
  type: "set"
  joint: 6  # axis e
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0

- task: "joint_limit"
  joint: 7  # axis d
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0

- task: "joint_limit"
  joint: 8  # axis c
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0

- task: "joint_limit"
  joint: 9  # axis b
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0

- task: "joint_limit"
  joint: 2  # Z-axis (depth)
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0

- task: "collision_plane"
  priority: 1
  upper: 0.0
  lower: 0.0
  p1: [0.1, 0.1, 0.1]
  p2: [0.1, 0.1, 0.1]
  p3: [0.1, 0.1, 0.1]
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0

- task: "end_effector_pose"
  priority: 2
  gain: 0.0

- task: "vehicle_roll_pitch"
  priority: 3
  gain: 0.0

- task: "vehicle_yaw"
  priority: 4
  gain: 0.0
