- task: "joint_limit_set"
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0
  joint: 6  # axis b

- task: "joint_limit_set"
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0
  joint: 7  # axis c

- task: "joint_limit_set"
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0
  joint: 8  # axis d

- task: "joint_limit_set"
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0
  joint: 9  # axis e

- task: "joint_limit_set"
  joint: 2  # Z-axis (depth)
  priority: 1
  upper: 0.0
  lower: 0.0
  activation_threshold: 0.0
  deactivation_threshold: 0.0
  gain: 0.0

- task: "end_effector_pose_eq"
  priority: 2
  gain: 0.0

- task: "vehicle_roll_pitch_eq"
  priority: 3
  gain: 0.0
  roll: 0.0
  pitch: 0.0

- task: "vehicle_yaw_eq"
  priority: 4
  gain: 0.0
  yaw: 0.0
